core/urls.py
from django.urls import path , include
from . import views

app_name="core"

urlpatterns = [
    # HomePage
    path('', views.index  , name="index" ) , 
    path('products/', views.productListView  , name="product-list" ) , 

    # Category
    path('category/', views.categoryListView  , name="category-list" ) , 
    path('category/<cid>/', views.categoryProductListView  , name="category-product-list" ) , 

    # Vendor
    path('vendors/', views.vendorListView  , name="vendor-list" ) , 
    path('vendor/<vid>/', views.vendorDetailView  , name="vendor-detail" ) , 

    # Product
    path('product/<pid>/', views.productDetailView  , name="product-detail" ) , 

    # Tags
    path('products/tag/<slug:tag_slug>/', views.tagList  , name="tags" ) , 


    # Add Review
    path('ajax-add-review/<pid>/', views.ajaxAddReview  , name="ajax-add-review" ) , 


    # Search
    path('search/', views.searchView  , name="search" ) , 

    # Filter
    path('filter-products/', views.filterProductView  , name="filter-product" ) , 


    # Cart
    path('cart/', views.cartView  , name="cart" ) , 
    path('add-to-cart/', views.addToCartView  , name="add-to-cart" ) , 
    path('delete-from-cart/', views.deleteFromCartView  , name="delete-from-cart" ) , 
    path('update-cart/', views.updateProductFromCartView  , name="update-cart" ) , 


    # Checkout
    path('checkout/<oid>', views.checkoutView  , name="checkout" ) , 


    # PayPal
    path('paypal/',include('paypal.standard.ipn.urls') ) , 


    # Payment
        # paypal
    path('payment-completed/<oid>/', views.paymentCompleteView  , name="payment-completed" ) , 
    path('payment-failed/', views.paymentFailedView  , name="payment-failed" ) , 
        # stripe
    path('api/create_checkout_session/<oid>/', views.createCheckoutSession  , name="create_checkout_session" ) ,

    # Customer Dashboard
    path('dashboard/', views.customerDashboardView  , name="dashboard" ) , 


    # Order Detail
    path('dashboard/order/<id>', views.order_detail  , name="order-detail" ) , 


    # Making Address Default
    path('make-default-address/', views.defaultAddress  , name="make-default-address" ) , 


    #  Wishlist
    path('wishlist/', views.wishlistPageView  , name="wishlist" ) , 
    path('toggle-wishlist/', views.toggleWishlist  , name="toggle-wishlist" ) , 
    path('delete-product-from-wishlist/', views.deleteFromWishlistView  , name="delete-product-from-wishlist" ) , 


    # Contact
    path('contact/', views.contactView  , name="contact" ) , 
    path('contact-us/', views.ajaxContactView  , name="contact-us" ) , 


    # New Routes
    path('save-checkout-info/', views.saveCheckoutInfo  , name="save-checkout-info" ) , 


    # # Add To Wishlist
    # path('add-to-wishlist/', views.addToWishlist  , name="add-to-wishlist" ) , 
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls') ) , 
    path('user/',include('userauths.urls') ) , 
    path('useradmin/',include('useradmin.urls') ) , 


    path('ckeditor',include('ckeditor_uploader.urls') ) , 
    path('paypal/',include('paypal.standard.ipn.urls') ) , 

]




if settings.DEBUG ==True:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write Review"}))

    class Meta:
        model = ProductReview
        fields = ['review' , 'rating']

core/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from .models import Product , Coupon , Category , Vendor , CartOrder , CartOrderItem , ProductImages , Wishlists , Address , ProductReview 
from userauths.models import ContactUs , Profile
from django.db.models import Count , Avg
from taggit.models import Tag
from .forms import ProductReviewForm
from django.http import  JsonResponse
from django.template.loader import render_to_string
from django.db.models import Min, Max
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.db.models.functions import ExtractMonth
import calendar
import stripe




# Create your views here.



def index(request):
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published" , featured=True)
    

    context = {
        "products" : products,
        
    }
    return render(request , 'core/index.html' , context)



def productListView(request):
    products= Product.objects.filter(product_status="published" )
    
    context = {
        "products" : products
    }
    return render(request , 'core/product-list.html' , context)



def categoryListView(request):
    categories = Category.objects.all()
    # categories = Category.objects.all().annotate(product_count=Count("product"))
    context = {
        "categories" : categories
    }
    return render(request , 'core/category-list.html' , context)



def categoryProductListView(request , cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status = "published" , category = category)

    context={
        "category" : category ,
        "products" : products ,
    }
    return render(request , "core/category-product-list.html" ,context)



def vendorListView(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors" : vendors,
    }
    return render(request , "core/vendor-list.html" , context)



def vendorDetailView(request , vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(product_status = "published" , vendor=vendor)
    context = {
        "vendor" : vendor,
        "products" : products,
    }
    return render(request , "core/vendor-detail.html" , context)



def productDetailView(request , pid):
    product = Product.objects.get( pid=pid)
    # product = get_object_or_404(Product , pid=pid)
    products = Product.objects.filter(category = product.category , product_status = "published").exclude(pid=pid)[:4]

    # Getting All Reviews Related To Product

    reviews = ProductReview.objects.filter(product=product).order_by("-id")

    # Getting Average Review
    average_rating = ProductReview.objects.filter(product=product ).aggregate(rating=Avg('rating'))


    # Product Review Form
    review_form = ProductReviewForm

    make_review = True

    if request.user.is_authenticated:
        uesr_review_count = ProductReview.objects.filter(user=request.user , product=product).count()
        if uesr_review_count >0 :
            make_review = False



    product_images = product.product_images.all()
    
    context = {
        "product" : product , 
        "product_images" : product_images , 
        "products" : products , 
        "reviews" : reviews , 
        "average_rating" : average_rating , 
        "review_form" : review_form , 
        "make_review" : make_review , 
    }
    return render(request , "core/product-detail.html"  ,context )



def tagList(request , tag_slug=None):
    products = Product.objects.filter( product_status = "published").order_by("-id")
    tag = None
    if tag_slug :
        tag = get_object_or_404(Tag , slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        "products":products,
        "tag":tag,

    }
    return render(request , "core/tag.html" , context)



def ajaxAddReview(request , pid):
    
    product = Product.objects.get(pid = pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user ,
        product = product ,
        review = request.POST['review' ],
        rating = request.POST['rating'],
    )
    context ={
        'user' :user.username ,
        'review' :request.POST['review' ] ,
        'rating' :request.POST['rating'] ,
    }
    average_rating = ProductReview.objects.filter(product=product ).aggregate(rating=Avg('rating'))

    return JsonResponse(
        {
            'bool' : True ,
        'context' : context ,
        'average_rating' : average_rating ,
        }
    )



def searchView(request):
    query = request.GET.get("q")
    products = Product.objects.filter(title__icontains = query ).order_by("-date")

    context = {

        "products": products ,
        "query":query ,
    }

    return render(request , "core/search.html"  ,context )



def filterProductView(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET["min_price"]
    max_price = request.GET["max_price"]

    products = Product.objects.filter(product_status="published" ).order_by("-id").distinct()

    products = products.filter(price__gte = min_price) # gte mean greater than or equal to
    products = products.filter(price__lte = max_price) # lte mean less than or equal to



    if (len(categories) >0 ):
        products = products.filter(category__id__in=categories).distinct()

    if (len(vendors) >0 ):
        products = products.filter(vendor__id__in=vendors).distinct()

    context = {
        "products":products,
    }
    product_count = products.count()

    data = render_to_string("core/async/product-list.html" , context)

    return JsonResponse({
        "data":data ,
        "product_count":product_count ,
        

    })



@login_required
def addToCartView(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] ={ 
        'title' : request.GET['title'] ,
        'qty' : request.GET['qty'] ,
        'price' : request.GET['price'] ,
        'image' : request.GET['image'] ,
        'pid' : request.GET['pid'] ,
    }

    if 'cart_data_obj' in request.session :
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[request.GET['id']]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else :
            cart_data= request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data

    else :
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({
        'data' : request.session['cart_data_obj'] ,
        'totalCartItems' : len(request.session['cart_data_obj'])
    })



def cartView(request):
    cart_total_amount =0
    if 'cart_data_obj' in request.session:
        for product_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            
        context = {
        'cart_data' : request.session['cart_data_obj'] ,
        'totalCartItems' : len(request.session['cart_data_obj']) ,
        'cart_total_amount':cart_total_amount
    }
        return render(request , "core/cart.html" , context)
    
    else:
        context = {
        'cart_data' : '' ,
        'totalCartItems' : 0 ,
        'cart_total_amount':cart_total_amount
    }
        messages.warning(request , "Your Cart Is Empty")
        return render(request , "core/cart.html" , context)



def deleteFromCartView(request):
    product_id = str(request.GET['id'])

    if 'cart_data_obj' in request.session :
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total_amount =0
    if 'cart_data_obj' in request.session:
        for product_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

        

    context = render_to_string("core/async/cart-list.html" , {
        'cart_data' : request.session['cart_data_obj'] ,
        'totalCartItems' : len(request.session['cart_data_obj']) ,
        'cart_total_amount':cart_total_amount
    })
    return JsonResponse({
        "data" : context ,
        'totalCartItems' : len(request.session['cart_data_obj']) ,
    })

def updateProductFromCartView(request):
    product_id = str(request.GET['id'])
    product_qty = int(request.GET['qty'])
    if 'cart_data_obj' in request.session :
        if product_id in request.session['cart_data_obj']:
            request.session['cart_data_obj'][product_id]['qty'] = product_qty
            request.session.modified = True

    cart_total_amount =0
    if 'cart_data_obj' in request.session:
        for product_id , item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

        

    context = render_to_string("core/async/cart-list.html" , {
        'cart_data' : request.session['cart_data_obj'] ,
        'totalCartItems' : len(request.session['cart_data_obj']) ,
        'cart_total_amount':cart_total_amount
    })
    return JsonResponse({
        "data" : context ,
        'totalCartItems' : len(request.session['cart_data_obj']) ,
    })



# @login_required
# def checkoutView(request):
#     cart_data = request.session.get("cart_data_obj", {})
    
#     if not cart_data:  # Redirect if cart is empty
#         return redirect("core:cart")

templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% load mathfilters %}

    

{% block content %}
    



    <main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{totalCartItems}}</span> products in your cart</h6>
                        <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" >Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col" >Refresh</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for product_id ,item in cart_data.items %}
                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{%url 'core:product-detail' item.pid%}">{{item.title}}</a></h6>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width:90%">
                                                </div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> (4.0)</span>
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-body">${{item.price |floatformat:2}} </h4>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <div class="detail-extralink mr-15">
                                            <div class="detail-qty border radius">
                                                {% comment %} <a href="#" class="qty-down"><i class="fi-rs-angle-small-down"></i></a> {% endcomment %}
                                                <input type="number" name="quantity" class="qty-val" value="{{item.qty}}" min="1">
                                                {% comment %} <a href="#" class="qty-up"><i class="fi-rs-angle-small-up"></i></a> {% endcomment %}
                                            </div>
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-brand">${{ item.price|mul:item.qty|floatformat:2 }} </h4>
                                    </td>
                                    <td class="action text-center" data-title="Update"><button style="border: 0; background: none;" class="text-body update-product" data-product={{product_id}}><i class="fi-rs-refresh"></i></button></td>
                                    <td class="action text-center" data-title="Remove"><button style="border: 0; background: none;" class="text-body delete-product" data-product={{product_id}}><i class="fi-rs-trash"></i></button></td>
                                </tr>
                                {% endfor %}
                                    


                            </tbody>
                        </table>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <div class="cart-action d-flex justify-content-between">
                        <form method="POST" action="{% url 'core:save-checkout-info' %}">
                            {% csrf_token %}
                        
                            <div class="row">
                                <!-- Bio Data Section -->
                                <div class="col-md-6">
                                    <div class="card shadow-sm border-0 mb-4">
                                        <div class="card-header text-white">
                                            <h4 class="mb-0">Bio Data</h4>
                                        </div>
                                        <div class="card-body">
                                            <div class="mb-3">
                                                <label for="fullName" class="form-label">Full Name</label>
                                                <input type="text" class="form-control" id="fullName" name="full_name" placeholder="Enter full name" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="mobile" class="form-label">Mobile</label>
                                                <input type="tel" class="form-control" id="mobile" name="mobile" placeholder="Enter mobile number" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="address" class="form-label">Email</label>
                                                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        
                                <!-- Shipping Details Section -->
                                <div class="col-md-6">
                                    <div class="card shadow-sm border-0 mb-4">
                                        <div class="card-header text-white">
                                            <h4 class="mb-0">Shipping Details</h4>
                                        </div>
                                        <div class="card-body">
                                            <div class="mb-3">
                                                <label for="shippingAddress" class="form-label">Address</label>
                                                <input type="text" class="form-control" id="shippingAddress" name="shipping_address" placeholder="Enter shipping address" required>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-4 mb-3">
                                                    <label for="city" class="form-label">City</label>
                                                    <input type="text" class="form-control" id="city" name="city" placeholder="Enter city" required>
                                                </div>
                                                <div class="col-md-4 mb-3">
                                                    <label for="state" class="form-label">State</label>
                                                    <input type="text" class="form-control" id="state" name="state" placeholder="Enter state" required>
                                                </div>
                                                <div class="col-md-4 mb-3">
                                                    <label for="country" class="form-label">Country</label>
                                                    <input type="text" class="form-control" id="country" name="country" placeholder="Enter country" required>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        
                        
                        
                        
                    </div>

                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">${{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">$0</h4></td> </tr> <tr>

                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Tax</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">$0</h4></td> </tr> <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Discount</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">$0</h4></td> </tr> <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">${{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>


                        {% if totalCartItems %}
                            <button type="submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                            
                        {% endif %}
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </main>



    
{% endblock content %}
        
    
    

templates/core/payment-complete.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
    <div class="row justify-content-center pt-lg-4 text-center" style="margin-bottom: 200px; margin-top: 100px;">
        <div class="col-lg-5 col-md-7 col-sm-9">
            <h1 class="display-404 py-lg-3">Payment Completed</h1>
            <h2 class="h3 mb-4">Your Order successfully placed. Order ID #{{order.oid}}</h2>
            <p class="fs-md mb-4"><a href="#">Contact us</a>if you have any issue or question</p>
        </div>
    </div>
{% endblock content %}
    

templates/core/payment-failed.html
{% extends 'partials/base.html' %}
{% load static %}


    

{% block content %}
    

    
    <main class="main page-404">
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto text-center">
                        <p class="mb-20"><img src="{% static 'assets/imgs/page/failed.PNG' %}" alt="Failed" class="hover-up" />
                        </p>
                        <h1 class="display-2 mb-30">Payment Failed</h1>
                        <p class="font-lg text-grey-700 mb-30">
                            Try Again Later<br />
                        </p>
                        
                        <a class="btn btn-default submit-auto-width font-xs hover-up mt-30" href="{% url 'core:index'%}"><i class="fi-rs-home mr-5"></i> Back To Home Page</a>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}